export enum INDICACION_ESPECIAL_ACTIONS {
  LIVE_CREATED = '[INDICACION_ESPECIAL] LIVE CREATED',
  LIVE_UPDATED = '[INDICACION_ESPECIAL] LIVE UPDATED',
  LIVE_DELETED = '[INDICACION_ESPECIAL] LIVE DELETED',
}
